DACSWebBanFlower/Controllers/AccessController.cs
using DACSWebBanFlower.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Security.Cryptography;
using DACSWebBanFlower.Models.Authentication;

namespace DACSWebBanFlower.Controllers
{
    public class AccessController : Controller
    {
        private readonly QlbanFlowerContext _db;
        private TUser AuthenticateUser(string username, string password)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin người dùng dựa trên tên đăng nhập và mật khẩu
            var user = _db.TUsers.FirstOrDefault(u => u.Id == username && u.Password == password);
            return user;
        }
        public AccessController(QlbanFlowerContext db)
        {
            _db = db;
        }

        //Login form
        [HttpGet]
        public IActionResult Login()
        {
            // Kiểm tra xem người dùng đã đăng nhập chưa
            if (HttpContext.Session.GetString("Id") != null)
            {
                // Nếu đã đăng nhập, chuyển hướng đến trang "Index"
                return RedirectToAction("Index", "Home");
            }

            // Nếu chưa đăng nhập, hiển thị trang Index chứa thông tin "Login (chưa đăng nhập)"
            return View();
        }
        [HttpPost]
        public IActionResult Login(TUser user)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xác thực người dùng
                var authenticatedUser = AuthenticateUser(user.Id, user.Password);

                if (authenticatedUser != null)
                {
                    // Kiểm tra quyền truy cập của người dùng và điều hướng đến trang tương ứng
                    if (authenticatedUser.LoaiUser == 1) // Quyền admin
                    {
                        // Điều hướng đến trang admin
                        return RedirectToAction("Index", "Admin", new { area = "Admin" });
                    }
                    else if (authenticatedUser.LoaiUser == 2) // Quyền khách hàng
                    {
                        // Đăng nhập thành công, thiết lập session và chuyển hướng đến trang ShopIndex
                        HttpContext.Session.SetString("Id", authenticatedUser.Id);
                        // Điều hướng đến trang chủ
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    // Đăng nhập thất bại, hiển thị trang đăng nhập với thông báo lỗi
                    ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    return View();
                }
            }

            // Dữ liệu đầu vào không hợp lệ, hiển thị lại trang đăng nhập
            return View(user);
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            // Lấy trang trước đó từ session
            string? previousUrl = HttpContext.Session.GetString("PreviousUrl");

            if (!string.IsNullOrEmpty(previousUrl))
            {
                // Xóa trang trước đó từ session
                HttpContext.Session.Remove("PreviousUrl");
                return Redirect(previousUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        //Register form
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(TUser user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var existingUser = _db.TUsers.FirstOrDefault(u => u.Id == user.Id);
                    if (existingUser == null)
                    {

                        _db.TUsers.Add(user);
                        _db.SaveChanges();

                        HttpContext.Session.SetString("Id", user.Id);

                        // Hiển thị thông báo thành công
                        TempData["SuccessMessage"] = "User registered successfully.";

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Username already exists.");
                    }
                }
                return View(user);
            }
            catch (Exception ex)
            {
                // Log lỗi để dễ dàng xác định và sửa lỗi
                // Đồng thời, bạn có thể hiển thị thông báo lỗi hoặc thực hiện xử lý khác tùy thuộc vào nhu cầu của bạn
                // Ví dụ: Log lỗi và chuyển hướng đến một trang lỗi hoặc hiển thị thông báo lỗi
                Console.WriteLine($"An error occurred: {ex.Message}");
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                return View(user);
            }
        }
    }
}

DACSWebBanFlower/Views/Access/Login.cshtml
@{
    Layout = null;
}
@model TUser
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Team~Alone</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../LayoutAdmin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../LayoutAdmin/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../LayoutAdmin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../LayoutAdmin/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth">
                <div class="row flex-grow">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left p-5">
                            <div class="brand-logo align-items-center d-flex justify-content-center">
                                <img src="../../LayoutAdmin/assets/images/LogoTeam.png" style="width: 200px; height: 100%;padding: 0;" alt="Team Alone">
                            </div>

                            <h4>Hello! let's get started</h4>

                            <h6 class="font-weight-light">Sign in to continue.</h6>
                            @*<form class="pt-3">*@
                            @using (Html.BeginForm("Login", "Access", FormMethod.Post))
                            {
                                <div class="form-group">

                                    @Html.TextBoxFor(x => x.Id, new { @class = "form-control form-control-lg", placeholder = "Id", required = "required", autofocus = "autofocus" })

                                    @*<input type="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Username">*@
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Password, new { @class = "form-control form-control-lg", type = "password", placeholder = "Password" })

                                    @*<input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password">*@
                                </div>

                                <div class="mt-3">
                                    <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit">Đăng Nhập</button>
                                    @*<a class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" href="../../index.html">SIGN IN</a>*@
                                </div>
                                <div class="my-2 d-flex justify-content-between align-items-center">
                                    <div class="form-check">
                                        <label class="form-check-label text-muted">
                                            <input type="checkbox" class="form-check-input"> Keep me signed in
                                        </label>
                                    </div>
                                    <a href="#" class="auth-link text-black">Forgot password?</a>
                                </div>
                                <div class="mb-2">
                                    <button type="button" class="btn btn-block btn-facebook auth-form-btn">
                                        <i class="mdi mdi-facebook me-2"></i>Connect using facebook
                                    </button>
                                </div>
                                <div class="text-center mt-4 font-weight-light">
                                    Don't have an account? <a href="@Url.Action("Register", "Access")" class="text-primary">Create</a>
                                </div>
                            }@*</form>*@
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../LayoutAdmin/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../LayoutAdmin/assets/js/off-canvas.js"></script>
    <script src="../../LayoutAdmin/assets/js/hoverable-collapse.js"></script>
    <script src="../../LayoutAdmin/assets/js/misc.js"></script>
    <!-- endinject -->
</body>
</html>

DACSWebBanFlower/Views/Access/Register.cshtml
@{
    Layout = null;
}
@model DACSWebBanFlower.Models.RegisterModels.RegisterModel
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Register</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../LayoutAdmin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../LayoutAdmin/assets/vendors/css/vendor.bundle.base.css">
    <!-- CSS đang được import -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../LayoutAdmin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../LayoutAdmin/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center auth">
                <div class="row flex-grow">
                    <div class="col-lg-4 mx-auto">
                        <div class="auth-form-light text-left p-5">
                            <div class="brand-logo">
                                <img src="../../LayoutAdmin/assets/images/logo.svg">
                            </div>
                            <h4>Hello! Let's get started</h4>
                            <h6 class="font-weight-light">Create an account.</h6>
                            @using (Html.BeginForm("Register", "Access", FormMethod.Post))
                            {
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Id, new { @class = "form-control form-control-lg", placeholder = "Id", required = "required", autofocus = "autofocus" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Password, new { @class = "form-control form-control-lg", type = "password", placeholder = "Password", required = "required" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.TenKhachHang, new { @class = "form-control form-control-lg", placeholder = "Full Name", required = "required" })
                                </div>

                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control form-control-lg", placeholder = "Phone Number" })
                                </div>

                                <div class="mt-3">
                                    <button class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" type="submit">Register</button>
                                </div>

                                <div class="text-center mt-4 font-weight-light">
                                    Already have an account? <a href="@Url.Action("Login", "Access")" class="text-primary">Sign in</a>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- plugins:js -->
    <script src="../../LayoutAdmin/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../LayoutAdmin/assets/js/off-canvas.js"></script>
    <script src="../../LayoutAdmin/assets/js/hoverable-collapse.js"></script>
    <script src="../../LayoutAdmin/assets/js/misc.js"></script>
    <!-- endinject -->
</body>
</html>